// responsible-ai-mfe-react/apps/web/app/components/benchmarking/BenchmarkingView.tsx
import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@workspace/ui/components/card"

import { apiClient, getApiConfig } from "../../lib/apiClient"

interface LeaderboardRow {
  model: string
  toxicity: string
  pii: string
  adv: string
  overall: string
}

function formatScore(value: unknown): string {
  if (typeof value !== "number") return "N/A"
  const normalized = value <= 1 ? value * 100 : value
  return `${normalized.toFixed(1)}%`
}

export default function BenchmarkingView() {
  const [leaderboard, setLeaderboard] = React.useState<LeaderboardRow[]>([
    { model: "Gemini 1.5 Pro", toxicity: "98.5%", pii: "97.8%", adv: "94.5%", overall: "96.9%" },
    { model: "GPT-4o", toxicity: "97.2%", pii: "96.5%", adv: "93.2%", overall: "95.6%" },
    { model: "Llama-3-70B", toxicity: "95.4%", pii: "93.1%", adv: "89.8%", overall: "92.7%" },
  ])

  React.useEffect(() => {
    const config = getApiConfig()
    const endpoint =
      config.SecurityLLMLeaderboard && config.LeaderboardEndpoint
        ? `${config.SecurityLLMLeaderboard}${config.LeaderboardEndpoint}scores/getScores?category=fairness`
        : "/api/v1/trustllm/scores/getScores?category=fairness"

    apiClient<any[]>(endpoint, { service: "leaderboard" })
      .then(data => {
        if (!Array.isArray(data) || data.length === 0) return

        const mapped: LeaderboardRow[] = data
          .map((item: any) => {
            if (!item || typeof item !== "object") return null
            const modelName = Object.keys(item)[0]
            if (!modelName) return null

            const metrics = item[modelName] || {}
            return {
              model: modelName,
              toxicity: formatScore(metrics.toxicity ?? metrics.toxicity_score ?? metrics.Toxicity),
              pii: formatScore(metrics.privacy ?? metrics.pii ?? metrics.privacy_score ?? metrics.Privacy),
              adv: formatScore(
                metrics.robustness ?? metrics.adversarial_robustness ?? metrics.attack_score ?? metrics.Adversarial
              ),
              overall: formatScore(metrics.overall ?? metrics.score ?? metrics.fairness ?? metrics.Fairness),
            }
          })
          .filter(Boolean) as LeaderboardRow[]

        if (mapped.length > 0) {
          setLeaderboard(mapped)
        }
      })
      .catch(err => {
        console.warn("Failed to fetch leaderboard data", err)
      })
  }, [])

  return (
    <Card className="border-slate-800 bg-slate-900/30 text-slate-100">
      <CardHeader>
        <CardTitle className="text-lg">LLM Safety Leaderboard</CardTitle>
        <CardDescription className="text-slate-400">Benchmark comparison of model robustness against guardrail tests</CardDescription>
      </CardHeader>
      <CardContent>
        <table className="w-full text-left border-collapse text-xs">
          <thead>
            <tr className="border-b border-slate-800 text-slate-400 font-semibold">
              <th className="py-3">Model</th>
              <th className="py-3">Toxicity Resistance</th>
              <th className="py-3">PII Leakage Shield</th>
              <th className="py-3">Adversarial Robustness</th>
              <th className="py-3">Overall Safety Score</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 text-slate-300">
            {leaderboard.map((row) => (
              <tr key={row.model} className="hover:bg-slate-800/10">
                <td className="py-4 font-semibold text-slate-200">{row.model}</td>
                <td className="py-4">{row.toxicity}</td>
                <td className="py-4">{row.pii}</td>
                <td className="py-4">{row.adv}</td>
                <td className="py-4 text-emerald-400 font-semibold">{row.overall}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </CardContent>
    </Card>
  )
}

// responsible-ai-mfe-vue/src/views/BenchmarkingView.vue
<template>
  <section class="rai-card p-6">
    <header>
      <h2 class="text-lg font-semibold text-[#0f2b2c]">LLM Safety Leaderboard</h2>
      <p class="mt-1 text-sm text-[#305669]/70">
        Benchmark comparison of model robustness against guardrail tests
      </p>
    </header>

    <div class="mt-6 overflow-x-auto">
      <table class="w-full border-collapse text-left text-xs">
        <thead>
          <tr class="border-b border-[#e6dece] text-[#305669]/70">
            <th class="py-3 font-semibold">Model</th>
            <th class="py-3 font-semibold">Toxicity Resistance</th>
            <th class="py-3 font-semibold">PII Leakage Shield</th>
            <th class="py-3 font-semibold">Adversarial Robustness</th>
            <th class="py-3 font-semibold">Overall Safety Score</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-[#e6dece] text-[#305669]">
          <tr v-for="row in leaderboard" :key="row.model" class="hover:bg-[#faf7f0]">
            <td class="py-4 font-semibold text-[#0f2b2c]">{{ row.model }}</td>
            <td class="py-4">{{ row.toxicity }}</td>
            <td class="py-4">{{ row.pii }}</td>
            <td class="py-4">{{ row.adv }}</td>
            <td class="py-4 font-semibold text-emerald-400">{{ row.overall }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>

<script setup>
import { onMounted, ref } from 'vue';

const leaderboard = ref([
  { model: 'Gemini 1.5 Pro', toxicity: '98.5%', pii: '97.8%', adv: '94.5%', overall: '96.9%' },
  { model: 'GPT-4o', toxicity: '97.2%', pii: '96.5%', adv: '93.2%', overall: '95.6%' },
  { model: 'Llama-3-70B', toxicity: '95.4%', pii: '93.1%', adv: '89.8%', overall: '92.7%' }
]);

function formatScore(value) {
  if (typeof value !== 'number') {
    return 'N/A';
  }

  const normalized = value <= 1 ? value * 100 : value;
  return `${normalized.toFixed(1)}%`;
}

onMounted(async () => {
  try {
    const response = await fetch('/api/v1/trustllm/scores/getScores?category=fairness');
    if (!response.ok) {
      return;
    }

    const data = await response.json();
    if (!Array.isArray(data) || !data.length) {
      return;
    }

    const mapped = data
      .map(item => {
        const modelName = Object.keys(item || {})[0];
        if (!modelName) {
          return null;
        }

        const metrics = item[modelName] || {};
        return {
          model: modelName,
          toxicity: formatScore(metrics.toxicity ?? metrics.toxicity_score ?? metrics.Toxicity),
          pii: formatScore(metrics.privacy ?? metrics.pii ?? metrics.privacy_score ?? metrics.Privacy),
          adv: formatScore(
            metrics.robustness ?? metrics.adversarial_robustness ?? metrics.attack_score ?? metrics.Adversarial
          ),
          overall: formatScore(metrics.overall ?? metrics.score ?? metrics.fairness ?? metrics.Fairness)
        };
      })
      .filter(Boolean);

    if (mapped.length) {
      leaderboard.value = mapped;
    }
  } catch (error) {
    console.warn('Failed to fetch leaderboard data', error);
  }
});
</script>
