// responsible-ai-mfe-react/apps/web/app/components/account/PasswordView.tsx
import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@workspace/ui/components/card"
import { Label } from "@workspace/ui/components/label"
import { Input } from "@workspace/ui/components/input"
import { Button } from "@workspace/ui/components/button"
import { apiClient } from "../../lib/apiClient"

interface PasswordForm {
  currentPassword: string
  newPassword: string
  confirmPassword: string
}

export default function PasswordView() {
  const [loading, setLoading] = React.useState(false)
  const [success, setSuccess] = React.useState(false)
  const [error, setError] = React.useState("")
  const [passwords, setPasswords] = React.useState<PasswordForm>({
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  })

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPasswords({ ...passwords, [e.target.name]: e.target.value })
  }

  const handleSave = async () => {
    setLoading(true)
    setSuccess(false)
    setError("")

    if (passwords.newPassword !== passwords.confirmPassword) {
      setError("New password and confirm password do not match.")
      setLoading(false)
      return
    }

    try {
      await apiClient("/account/change-password", {
        service: "backend",
        method: "POST",
        body: JSON.stringify({
          currentPassword: passwords.currentPassword,
          newPassword: passwords.newPassword,
        }),
      })
      setSuccess(true)
      setPasswords({ currentPassword: "", newPassword: "", confirmPassword: "" })
    } catch (err: any) {
      setError(err.message || "Failed to update password")
    } finally {
      setLoading(false)
    }
  }

  return (
    <Card className="border-slate-800 bg-slate-900/30 text-slate-100 max-w-xl">
      <CardHeader>
        <CardTitle className="text-lg">Change Password</CardTitle>
        <CardDescription className="text-slate-400">Update your account password</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {success && <div className="text-emerald-400 text-sm">Password updated successfully.</div>}
        {error && <div className="text-red-400 text-sm">{error}</div>}
        
        <div className="space-y-2">
          <Label className="text-xs text-slate-300">Current Password</Label>
          <Input 
            name="currentPassword" 
            type="password"
            value={passwords.currentPassword} 
            onChange={handleChange}
            className="bg-slate-950 border-slate-800 text-slate-200" 
          />
        </div>
        <div className="space-y-2">
          <Label className="text-xs text-slate-300">New Password</Label>
          <Input 
            name="newPassword" 
            type="password"
            value={passwords.newPassword} 
            onChange={handleChange}
            className="bg-slate-950 border-slate-800 text-slate-200" 
          />
        </div>
        <div className="space-y-2">
          <Label className="text-xs text-slate-300">Confirm New Password</Label>
          <Input 
            name="confirmPassword" 
            type="password"
            value={passwords.confirmPassword} 
            onChange={handleChange}
            className="bg-slate-950 border-slate-800 text-slate-200" 
          />
        </div>
      </CardContent>
      <CardFooter>
        <Button onClick={handleSave} disabled={loading} className="bg-indigo-600 text-white hover:bg-indigo-500">
          {loading ? "Updating..." : "Update Password"}
        </Button>
      </CardFooter>
    </Card>
  )
}

// responsible-ai-shell-vue/src/views/PasswordView.vue
<template>
  <main class="flex min-h-screen items-center justify-center bg-[#faf7f0] p-6">
    <section class="rai-card w-full max-w-md p-8">
      <header class="space-y-1">
        <h1 class="flex items-center gap-2 text-xl font-semibold text-[#0f2b2c]">
          <Lock class="h-5 w-5 text-indigo-400" />
          Update Password
        </h1>
        <p class="text-xs text-[#305669]/70">
          Keep your TrustAI credentials safe and secure
        </p>
      </header>

      <form class="mt-6 space-y-4" @submit.prevent="handleSubmit">
        <label class="block">
          <span class="rai-label">Current Password</span>
          <input
            v-model="form.currentPassword"
            :type="showPasswords ? 'text' : 'password'"
            class="rai-input"
            placeholder="••••••••"
          />
        </label>
        <label class="block">
          <span class="rai-label">New Password</span>
          <input
            v-model="form.newPassword"
            :type="showPasswords ? 'text' : 'password'"
            class="rai-input"
            placeholder="••••••••"
          />
        </label>
        <label class="block">
          <span class="rai-label">Confirm New Password</span>
          <input
            v-model="confirmPassword"
            :type="showPasswords ? 'text' : 'password'"
            class="rai-input"
            placeholder="••••••••"
          />
        </label>

        <div class="flex justify-end text-xs text-[#305669]/70">
          <button class="hover:text-[#0f2b2c]" type="button" @click="showPasswords = !showPasswords">
            {{ showPasswords ? 'Hide Passwords' : 'Show Passwords' }}
          </button>
        </div>

        <p
          v-if="message"
          :class="[
            'rounded-xl px-3 py-3 text-sm',
            messageType === 'success'
              ? 'border border-emerald-500/20 bg-emerald-500/10 text-emerald-300'
              : 'border border-rose-500/20 bg-rose-500/10 text-rose-300'
          ]"
        >
          {{ message }}
        </p>

        <div class="flex justify-end gap-2 pt-2">
          <button class="rai-button-secondary h-9" type="button" @click="router.back()">
            Cancel
          </button>
          <button :disabled="submitting" class="rai-button-primary h-9" type="submit">
            {{ submitting ? 'Updating...' : 'Update Password' }}
          </button>
        </div>
      </form>
    </section>
  </main>
</template>

<script setup>
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Lock } from 'lucide-vue-next';

import { changePassword } from '../lib/auth';

const router = useRouter();
const confirmPassword = ref('');
const showPasswords = ref(false);
const submitting = ref(false);
const message = ref('');
const messageType = ref('success');
const form = reactive({
  currentPassword: '',
  newPassword: ''
});

async function handleSubmit() {
  message.value = '';

  if (!form.currentPassword || !form.newPassword) {
    messageType.value = 'error';
    message.value = 'Please complete both password fields.';
    return;
  }

  if (form.newPassword !== confirmPassword.value) {
    messageType.value = 'error';
    message.value = 'New password and confirmation do not match.';
    return;
  }

  submitting.value = true;

  try {
    await changePassword({ ...form });
    messageType.value = 'success';
    message.value = 'Password updated successfully.';
    form.currentPassword = '';
    form.newPassword = '';
    confirmPassword.value = '';
  } catch (error) {
    messageType.value = 'error';
    message.value = error.message || 'Unable to update password.';
  } finally {
    submitting.value = false;
  }
}
</script>
