// responsible-ai-mfe-vue/src/views/ModelsView.vue
<template>
  <section class="grid gap-6 md:grid-cols-3">
    <article
      v-for="model in models"
      :key="model.name"
      class="rai-card p-6 transition hover:border-[#d8cda9]"
    >
      <span class="block text-[10px] font-bold uppercase tracking-[0.24em] text-indigo-400">
        {{ model.type }}
      </span>
      <h2 class="mt-2 truncate text-base font-bold text-[#0f2b2c]">{{ model.name }}</h2>

      <div class="mt-5 space-y-3 pt-0 text-xs">
        <div class="flex justify-between">
          <span class="text-[#305669]/70">Precision:</span>
          <span class="font-semibold text-[#174143]">{{ model.precision }}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-[#305669]/70">Footprint:</span>
          <span class="font-semibold text-[#174143]">{{ model.size }}</span>
        </div>
      </div>
    </article>
  </section>
</template>

<script setup>
import { onMounted, ref } from 'vue';

import { getCatalogValue, loadCatalog } from '../lib/catalog';
import { request } from '../lib/http';
import { joinUrl } from '../lib/urls';
import { authState } from '../lib/auth';

const models = ref([]);

function currentUser() {
  return authState.account?.login || 'admin';
}

function workbenchEndpoint() {
  return joinUrl(getCatalogValue('Workbench'), getCatalogValue('Workbench_Model') || '/v1/workbench/model');
}

onMounted(async () => {
  try {
    await loadCatalog();
    const formData = new FormData();
    formData.append('userId', currentUser());
    const response = await request(workbenchEndpoint(), {
      method: 'POST',
      body: formData
    });

    const source = Array.isArray(response?.ModelDetails)
      ? response.ModelDetails
      : Array.isArray(response)
        ? response
        : [];

    models.value = source.map(item => ({
      name: item.ModelName || 'Unnamed Model',
      type: item.Type || 'Model',
      precision: item.Precision || 'Unknown',
      size: item.Size || 'Unknown'
    }));

    if (!models.value.length) {
      throw new Error('No models returned');
    }
  } catch (error) {
    console.warn('Failed to fetch models', error);
    models.value = [
      { name: 'pii-scrubber-bert-v2', type: 'Privacy Masker', precision: 'FP16', size: '340M params' },
      { name: 'toxicity-guardrail-classifier', type: 'Safety Moderator', precision: 'INT8', size: '110M params' },
      { name: 'legal-contract-compliance-auditor', type: 'Compliance Engine', precision: 'FP32', size: '7B params' }
    ];
  }
});
</script>

// responsible-ai-mfe-react/apps/web/app/components/ai-models/ModelsView.tsx
import * as React from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/ui/components/card"
import { apiClient, getApiConfig } from "../../lib/apiClient"

interface ModelDetail {
  ModelName?: string
  Type?: string
  Precision?: string
  Size?: string
}

interface ModelCard {
  name: string
  type: string
  precision: string
  size: string
}

export default function ModelsView() {
  const [models, setModels] = React.useState<ModelCard[]>([])

  React.useEffect(() => {
    const formData = new FormData()
    formData.append("userId", "admin") // Typically from auth context

    const config = getApiConfig()
    const endpoint =
      config.Workbench && config.Workbench_Model ? `${config.Workbench}${config.Workbench_Model}` : "/v1/workbench/model"

    apiClient<any>(endpoint, {
      method: "POST",
      service: "modelDetail",
      body: formData,
      skipAuth: false,
    })
      .then(data => {
        const source: ModelDetail[] = Array.isArray(data?.ModelDetails)
          ? data.ModelDetails
          : Array.isArray(data)
            ? data
            : []

        const mapped = source.map((m) => ({
          name: m.ModelName || "Unnamed Model",
          type: m.Type || "Model",
          precision: m.Precision || "Unknown",
          size: m.Size || "Unknown",
        }))
        setModels(mapped)
      })
      .catch(err => {
        console.warn("Failed to load models from API", err)
        setModels([
          { name: "pii-scrubber-bert-v2", type: "Privacy Masker", precision: "FP16", size: "340M params" },
          { name: "toxicity-guardrail-classifier", type: "Safety Moderator", precision: "INT8", size: "110M params" },
          { name: "legal-contract-compliance-auditor", type: "Compliance Engine", precision: "FP32", size: "7B params" },
        ])
      })
  }, [])

  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      {models.map((m) => (
        <Card key={m.name} className="border-slate-800 bg-slate-900/30 text-slate-100 hover:border-slate-700/80 transition-all">
          <CardHeader>
            <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest block">{m.type}</span>
            <CardTitle className="text-base font-bold truncate mt-1">{m.name}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 pt-0">
            <div className="flex justify-between text-xs">
              <span className="text-slate-500">Precision:</span>
              <span className="text-slate-300 font-semibold">{m.precision}</span>
            </div>
            <div className="flex justify-between text-xs">
              <span className="text-slate-500">Footprint:</span>
              <span className="text-slate-300 font-semibold">{m.size}</span>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
